build_space: build
catkin_make_args: []
cmake_args:
- -GEclipse CDT4 - Unix Makefiles
devel_space: devel
extend_path: null
install: false
install_space: install
isolate_devel: false
isolate_install: false
make_args: []
source_space: src
